### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by lassik** [gvol/emacs-memento-mori#12]
Ping @aksharvarma @doolio @mandarvaze @ury-marshak who have sent PRs.

(And @alraban @danielpza @lockywolf @mateialexandru @Thfvdb who might be interested.)

I am no longer concerned with my own death. Simultaneously, the practicalities of life are getting ever more complex and I have to be a bit more careful about allocating time.

Consequently, I'm no longer managing to find time to maintain this package. I'd like someone to take my place as the new maintainer.

Please decide among yourselves who it should be. When a consensus has been reached, I'll transfer this repo to that person's account. You will then get the source code, PRs, and issue tracker as they are. I'll also send a PR to MELPA so their recipe points to your account. I'll keep just a fork under my own account.

Thanks to all for you continued interest in this package, and sorry I'v been unresponsive.

**Comment by lassik** [comment]
P.S. If you prefer GitLab intea of GitHub, that is fine as long as someone (other than me :) figures out how to copy the issue tracker.

**Comment by doolio** [comment]
I'm just learning to programme so am probably the least qualified to take over maintaining this package. Saying that if nobody else wants to step up I can do so.

**Comment by ghost** [comment]
>I am no longer concerned with my own death. 

How did you manage?

**Comment by gvol** [comment]
As I mentioned in #1, I recently created https://gitlab.com/gvol/memento.el which is similar.  I would be willing to take this repo over and port my code on top of it, but it's up to you.

**Comment by lassik** [comment]
@gvol Fine. Let me know if you want me to transfer this repo to your GitHub account.

**Comment by gvol** [comment]
Sounds good to me.  Hopefully, with Christmas break coming up for me I'll be able to get everything in order pretty soon.

**Comment by gvol** [comment]
Thanks for creating this repo, and I wish you the best!

**Comment by lassik** [comment]
@gvol I pressed the button to transfer the repository to you. You probably have to accept the transfer on your end.

**Comment by lassik** [comment]
OK, all done!

@gvol is now the maintainer. I no longer need the package for myself, so feel free to take it in whatever direction you want.

Thank you very much for continuing the work.

**Comment by doolio** [comment]
Thanks @lassik for creating this package and ensuring its continued maintenance.
