### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by lassik** [gvol/emacs-memento-mori#19]
Hi. I just noticed that I never published the package to [MELPA Stable](https://stable.melpa.org/).

That has now been fixed. I created the git tag `0.1` and pushed the tag to @gvol's repository and to my own fork. The comment in `memento-mori.el` says `Version: 0.1.0`.

I placed the `0.1` tag at a commit just before the new `Maintainer` line was added, so `0.1` was the first and last release that I am responsible for. Future releases (0.2 and up) will be at @gvol's discretion.

MELPA has automatically built and published [the stable packge](https://stable.melpa.org/#/memento-mori). It does this every time you push a new git tag.

**Comment by gvol** [comment]
Ah, thank you @lassik!  I have now pushed tag 0.3.

Thanks again for creating this package.
