### ISSUE TITLE
Display thought-provoking quotes

### ISSUE THREAD

**Issue by lassik** [gvol/emacs-memento-mori#2]
It might be worth gathering some quotes about death, and how to approach life in the knowledge that it is limited. Sites about stoicism might be a good place to start.

There could be a simple command to display a random quote in the echo area. It would also be nice to set the contents of the `*scratch*` buffer to a random quote at Emacs startup (the variable `initial-scratch-message` can be used for this).

Would anyone else like these?

**Comment by doolio** [comment]
@gvol couldn't this now be satisfied with `memento-mori-mementos`?

**Comment by gvol** [comment]
Oh, sorry @doolio, I was just finishing up.  That said, I think quotes are a little different.  Mementos as they are written now always have some aspect of time in them, whereas a quote doesn't.  And, at least in my mind, the quotes are usually longer and less suitable for putting in the modeline etc.

Obviously, if mementos are enough for you then you don't need to use quotes.  

I just grabbed some quotes from a few websites, so I'm sure there are some better ones.
