### ISSUE TITLE
Consider removing customization message

### ISSUE THREAD

**Issue by doolio** [gvol/emacs-memento-mori#21]
The following message appears in the *Messages* buffer:

> You’ll get more out of memento-mori-mode if you customize it.
Try M-x customize-group memento-mori RET

This will irritate users eventually. The customization section in the README should be sufficient to make the same point.

**Comment by gvol** [comment]
This _should_ only show until they have set either `memento-mori-mementos` or `memento-mori-birth-date`.  The package used to warn until you set `memento-mori-birth-date` because that was the only option, but I can remove it if you think it will be too annoying.

**Comment by doolio** [comment]
With `memento-mori-birth-date` set to my DOB (via the customize interface and saved to settings.el) and `memento-mori-mementos`unchanged from the default I see the message. In fact, I see it twice. My initial `*Messages*` buffer upon logging in is below:

```
Loading Emacs...done (0.014s)
Loading /home/doolio/.emacs.d/init.el...
Loading /home/doolio/.emacs.d/settings.el (source)...
Loading elec-pair...done
Loading mb-depth...done
Loading paren...done
Loading /home/doolio/.emacs.d/settings.el (source)...done
You’ll get more out of memento-mori-mode if you customize it.
Try M-x customize-group memento-mori RET
Loading /home/doolio/.emacs.d/init.el...done (0.773s)
Loading /home/doolio/.emacs.d/var/recentf-save.el (source)...done
Loading /home/doolio/.emacs.d/init.el...done (1.209s) [after-init]
You’ll get more out of memento-mori-mode if you customize it.
Try M-x customize-group memento-mori RET
When done with this frame, type C-x 5 0
Formats have changed, recompiling...done
Updating buffer list...done
```
My configuration is as follows:

```emacs-lisp
(use-package memento-mori               ; Reminder of our mortality.
  :demand t
  :config (memento-mori-mode))
```

**Comment by doolio** [comment]
If instead I unset `memento-mori-birth-date` and leave `memento-mori-mementos` unchanged from the default I still see the message but only once (see below). But why are the default mementos not shown instead? 

```
Loading Emacs...done (0.016s)
Loading /home/doolio/.emacs.d/init.el...
Loading /home/doolio/.emacs.d/settings.el (source)...
Loading elec-pair...done
Loading mb-depth...done
Loading paren...done
Loading /home/doolio/.emacs.d/settings.el (source)...done
You’ll get more out of memento-mori-mode if you customize it.
Try M-x customize-group memento-mori RET
Error (use-package): memento-mori/:config: Symbol’s function definition is void: format-spec
Loading /home/doolio/.emacs.d/init.el...done (0.737s)
Loading /home/doolio/.emacs.d/var/recentf-save.el (source)...done
Loading /home/doolio/.emacs.d/init.el...done (1.210s) [after-init]
When done with this frame, type C-x 5 0
Formats have changed, recompiling...done
Updating buffer list...done
```

In addition, with this configuration I also observed an error warning:

```
Error (use-package): memento-mori/:config: Symbol’s function definition is void: format-spec
```

`memento-mori-string` is also the empty string.

If I then disable and then re-enable the mode I see the message twice but this time a default memento appears in the modeline. In this test the memento is "24.26583471151152 years since Y2K" but the corresponding format string contains "%.5Y" so shouldn't the precision be to 5 decimal places?
