### ISSUE TITLE
MELPA and screenshot

### ISSUE THREAD

**Issue by mandarvaze** [gvol/emacs-memento-mori#3]
Can you add a screenshot in the README (I noticed there isn't one - so maybe it contains just a screenshot?)

Also - please make this available on MELPA

Thanks.

**Comment by lassik** [comment]
It is now installable from MELPA :) https://melpa.org/#/memento-mori

If someone makes a pull request that adds a `README.md` with a `screenshot.png`, I'll accept it.

**Comment by lassik** [comment]
Closing since #5 has been merged. Thanks!
