### ISSUE TITLE
Use a variable for the suffix text in the modeline

### ISSUE THREAD

**Issue by aksharvarma** [gvol/emacs-memento-mori#7]
It would be nice if the "years old" part of the text can be made into a variable that can be changed, it takes up too much space on the modeline right now.

Maybe change the code in `memento-mori-update` to be something like:
`(format (concat " %.2f " memento-mori-suffix-text) (memento-mori-age))`

I could submit a pull request if the idea sounds reasonable, shouldn't be too difficult.

**Comment by gvol** [comment]
You can now customize `memento-mori-mementos` to give you whatever flexibility you want.
